### ISSUE TITLE
Multilingual findings

### ISSUE THREAD

**Issue by noraj** [GhostManager/Ghostwriter#130]
Another critical feature is having a Multilingual vulnerability database (findings library).

Pentesters from english-speaking countries are maybe the only ones that doesn't need this feature.
But in countries you will need to have a findings library in both English and your native language and some countries also have 2, 3 or more official languages.

**Comment by chrismaddalena** [comment]
That's a good point. This is supported in a roundabout way. Findings just need unique titles, so the same finding written in a second or third language can be added because the title strings wouldn't match. That makes it messy to maintain the finding, but it can be done.

It shouldn't be too difficult to engineer a way to create and link two or more versions for language options. It's not a feature I can work on immediately, but I definitely see its value and would like to add it.

**Comment by noraj** [comment]
It already exists in PwnDoc if you want to check how it's done there.

**Comment by ReverseBrain** [comment]
+1 on this. Normally I write reports in italian but sometimes happened that I had to write them in english, so having a multilingual support for findings would be great.

**Comment by noraj** [comment]
I don't see the benefits of stale bots…

**Comment by noraj** [comment]
I'll close it as it's not planned, and I don't want to fight against the useless stale bot by bumping every 30 days.
