### ISSUE TITLE
Idea: Add support for Mattermost notifications 

### ISSUE THREAD

**Issue by Cave-Johnson** [GhostManager/Ghostwriter#135]
It would be great to have Mattermost notifications in addition to the current Slack offering.
I believe this works in a similar way to slack by using a webhook URL

**Comment by swisskyrepo** [comment]
Based on my tests you can replace the Slack URL with a Mattermost Incoming WebHook , it works fine ;)

**Comment by chrismaddalena** [comment]
That's very cool to hear! Thanks for sharing, @swisskyrepo. I had been curious about that. That's a nice workaround for the time being. In the future, we can add a separate MatterMost WebHook setting so it's possible to use both.

**Comment by Cave-Johnson** [comment]
Is there anyway to do this in the new setup? I have tested with channel name and a mattermost webhook but although the test shows success nothing comes through

**Comment by chrismaddalena** [comment]
@Cave-Johnson You can make changes to your Slack/MatterMoast config here: /admin/commandcenter/slackconfiguration/

The Slack test sends a basic "Hello from Ghostwriter :wave:" message to the configured channel. Per MatterMost docs, swapping in a MatterMost webhook for the Slack webhook should "just work." The test will report success so long as the POST to the configured webhook worked and returned a 200 OK response.

Nothing has changed in Ghostwriter around Slack or notifications and MatterMost doesn't list any issues that seem related:

https://developers.mattermost.com/integrate/webhooks/incoming/#known-slack-compatibility-issues

If the designated channel is a person (e.g., @so-and-so), the last bullet in the known issues mentions an issue with DMs. Otherwise, it should work. The channel must be valid and not archived.
