### ISSUE TITLE
Evidence in Rich Text field placement issue

### ISSUE THREAD

**Issue by Gimpy42** [GhostManager/Ghostwriter#159]
Evidence in Rich text are is using **in line with text** wrapper instead of Top & Bottom wrapper. This doesn't happen when plain text is use. We are wondering if their is a way to make it Top & Bottom by default, add the option somehow or play with the template jinja function to obtain that result.
ex: 
{{p finding.description_rt }} 
![image](https://user-images.githubusercontent.com/19766005/117002362-76f6b280-acb1-11eb-8ee3-1e3e1f2fea2a.png)
![image](https://user-images.githubusercontent.com/19766005/117004609-3e0c0d00-acb4-11eb-82d7-f530af66e048.png)

Plain text and wanted rendering
![image](https://user-images.githubusercontent.com/19766005/117003554-fe90f100-acb2-11eb-9f8a-436e3c37b201.png)

**Comment by chrismaddalena** [comment]
Hey–yes, the images come in as inline images. The process looks like this:

1. Create a new paragraph (goes to a new line and starts a new block of OXML for a paragraph)
2. Add text a run to the paragraph
3. Add the image to that line
4. Add a second run to the paragraph (adds a line break and starts a new line)
5. Write the caption text
6. Create a new paragraph

This process effectively creates the Top & Bottom formatting. The image is on a new line below any preceding text and above the next text run. Applying Top & Bottom within the Word application anchors the image to move text above and below it as you move it anywhere on the page (floating image). Strangely, that seems to be what you have in your first screenshot.

The library we use does not currently support floating images (https://python-docx.readthedocs.io/en/latest/user/shapes.html), but I'm not sure that would fix your issue here.

I tried to reproduce this and could not, but I don't typically insert images into a table (I think that's a table in your screenshot). When I tried a table, I didn't see this. It could be related to table formatting.

What does the template look like?

Also, when you open the document, are there are any errors or prompts to recover the XML? If there is, Word might mangle the XML during recovery and create a floating image.
