### ISSUE TITLE
Bluecoat Categorisation check not working

### ISSUE THREAD

**Issue by spankywetfish** [GhostManager/Ghostwriter#16]
Fairly recently the bluecoat sitereview process was updated with additional checks to prevent automated use. I'm assuming this is why my bluecoat categorised domains return 'No Results' in the domain health section?

**Comment by chrismaddalena** [comment]
Bluecoat did make changes to their site to use an X-SRF-TOKEN header for requests. The latest commit, from a couple of days ago, addresses this and the check is working. You may encounter Bluecoat's CAPTCHA which will result in a "No Result" result. We're looking into programmatically solving CAPTCHAs, where possible. Pulling the latest code should fix the check for you.

Since we are tracking this as a limitation of these automated checks, I am closing this for now.

**Comment by spankywetfish** [comment]
Awesome, the update seems to have fixed the issue.
Nice work.

**Comment by chrismaddalena** [comment]
Awesome, glad to hear it :)
