### ISSUE TITLE
Change default font size in Finding Library

### ISSUE THREAD

**Issue by heyquentin** [GhostManager/Ghostwriter#167]
Is there a way to change the default font size from 12pt to something else in the Finding Library? I'd like each finding to be a different font size but as it stands I'd have to go and manually change each finding.

**Comment by chrismaddalena** [comment]
That depends on what you're wanting to do. Yes, you can edit the TinyMCE configuration to change the default. Under _/static/css_ there's a _wysiwyg_styles.css_ file that TinyMCE loads. You can add this to the bottom of the file to change the default font size to 14pt (or whatever you want):

`body { font-size: 14pt; }`

Save the file and then reload any open Ghostwriter webpages. You may need to hold SHIFT when you click refresh to tell your browser to clear its cache and re-fetch the CSS.

That changes how TinyMCE displays the text, but it doesn't apply a style to the text that will carry over to report output. In a Word document, the text size will be the text size configured for your "Normal" style.

If you select a font size from the editor's Format menu that will apply a style to the HTML that sets the size. That style will carry over to report output and override the style configured in the Word template.

**Comment by heyquentin** [comment]
Thanks for the response. Indeed it's the final report font size that I'm looking to change. I'd like to default the font size from the Format menu to 10pt instead of 12pt as I'm using the _rt variable to display the text in my final report.[ I've included a link to a screenshot](https://imgur.com/a/Moe9sbw) of one of my findings in the Finding Library. Is there a way to default all Findings in the Finding Library (as well as all findings imported into the Library) to 10pt? I thought perhaps Crispy Forms might have a way to default it but I haven't come across it yet.

**Comment by heyquentin** [comment]
I found a kinda-sorta workaround today. I wiped my Findings Library then edited a csv with all my findings in it to have font size tags in them. After importing and generating a report my Description, Mitigation, etc. is all 10pt now. If there's a better way to do this I'd love to know though.

**Comment by chrismaddalena** [comment]
@heyquentin Hey, sorry for the late follow-up. If you need to make changes to font size for a Word report, the best way to do that is to update the styles in your templates. Word's default is 12pt font for the body. That's the "Normal" style in the template.

Open your template, find "Normal" in the style gallery, right-click it, and click Modify. Then you can change the font style from 12pt to 10pt.

![image](https://user-images.githubusercontent.com/10526228/152060574-b4efc27d-1a26-4e66-b9b2-4f0fb19f2f3f.png)

Save the template after changing the style and re-upload it to Ghostwriter. You can do the same for any other styles, like headings. Repeat for all your templates.

Back in Ghostwriter, TinyMCE will still default to 12pt. That's just for the webpage, but could be confusing if you have a style guide that calls for 10pt and people are seeing 12pt in the editor. That's where you could do what you've done with setting the font-size value on paragraph tags, or you could use TinyMCE's content CSS to change the default display value.

I recommend changing the CSS (_wysiwyg_styles.css_) because setting font size in the HTML could lead to confusing problems down the road. The HTML styling overwrites the styling in the Word templates. That's why setting `font-size: 10pt` for your paragraph tags changed the font in your Word reports.

If you later decided you wanted body content to be 12pt, you'd have to remove `font-size: 10pt` styles in every finding tr change it to 10pt. The expected workflow is you would just update styles in your templates and upload the new versions.
