### ISSUE TITLE
Wiki down?

### ISSUE THREAD

**Issue by DemanNL** [GhostManager/Ghostwriter#171]
Hi,

The ghostwriter.wiki has been down for quite a while. I was wondering if the wiki is returning because it contains quite a bit of valuable documentation.

**Comment by DemanNL** [comment]
Ah I see, is it possible to edit the about section of the GhostWriter github page to include the correct URL? I have made a pull request to change the readme.md

**Comment by chrismaddalena** [comment]
I'm looking into now. The short explanation is we had to change to a redirect. That should be fine, but it doesn't seem to play nice if you use HTTPS. I'd rather not update all the links (because we do want to use those links with HTTPS), so I'm poking around GitBook to see what we can do.

If all else fails, yes, I'll get all the links sorted out as soon as I can.
