### ISSUE TITLE
Shepherd: Domain Status Filter Not Working Correctly

### ISSUE THREAD

**Issue by er4z0r** [GhostManager/Ghostwriter#176]
GW Version: v2.2.1, released 27 May 2021

I have several domains with Namecheap some of which have expired. And one, which I manually flagged as burned.

Observed behavior: 
The domain_list.html  with default filter set to "Available" also lists my expired and burned domains and shows them as available. The problem is easily detected for burned domains (because the burned status is visible in the table). For expired domains, you only notice it after clicking on the domain name (i.e. the expired status is shown correctly in the domain_detail.html)

Expected behavior:
A domain that is expired or burned should not be listed as available. It should be listed when filtering for "Expired" or "Burned"

**Comment by er4z0r** [comment]
It seems that what I observed is the result of changes (brun, expiry) only being made to the health_status and expired attributes but not domain_status. I was using the first  filter in the domain_list.html which [uses domain_status](https://github.com/GhostManager/Ghostwriter/blob/69bf30406942a0d6d114e21a90f2267cdfaee1c5/ghostwriter/shepherd/filters.py#L92).

I've verified this in my database (see. attached screenshot) 
![gw-domains-health](https://user-images.githubusercontent.com/286428/127307242-c857ad5a-ce1b-458d-b5a1-902b05e18e61.png)

From my understanding a domain should not be

- both expired and available (red markings)
- both healthy and burned (green markings)

Is this something conceptual I am not seeing or is it simply a bug?

**Comment by chrismaddalena** [comment]
The list filter is based on the `domain_status`, so if the domain is set to "Available" it'll appear that way in the filtered list. The `expired` boolean value is mostly used on the back-end as an easier way to check a domain's expiration status. If you schedule the `check_expiration` task the server will update `expired` and `domain_status` if the domain's expiration date is in the past and `auto_renew` is `False`.

Currently, nothing catches the discrepancy if you manually set `expired` to `True` and `domain_status` to Available. That's an oversight we'll address.

For "Burned" domains, those domains are considered available for checkout because a burned domain is not necessarily bad. There may be instances you don't mind using a domain that has a less than desirable categorization from a particular vendor or you see the VirusTotal scan that flagged the domain is older and low risk.

**Comment by chrismaddalena** [comment]
@er4z0r I had time to take another look at this. I wanted to make this easier to follow in cases like you described (domain is expired but status may still be set to "Available"). The `check_expiration()` background task should handle this, but there could be cases like you described.

Here's what I've done today. I'm open to your feedback before I push this.

First, I reviewed the table and made some changes. The "WHOIS Privacy" column was kind of unnecessary. I thought it would be much more useful to see the expiration date in the table. If the date is in the past it will appear in the same pastel red as the "Expired" and "Burned" status strings.

For the filter, I'm working on an additional checkbox that filters using this query when checked.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/10526228/158280456-a38ad1e0-efd6-4ef3-99e2-71fbbbefbb09.png">

If not checked (set to `False`):

`return queryset.filter(Q(expired=False) & Q(Q(expiration__gte=date.today()) | Q(auto_renew=True)))`

That will return only domains where the back-end `expired` boolean is `False` + the expiration date is in the future or `auto_renew` is set to `True`. That _should_ catch situations where domains have not been updated by the `check_expiration()` task and have:

* the "Available" status, but `expiration` is in the past and `auto_renew` is `False`
* an `expiration` in the past but `auto_renew` is `True`
* any combination of `domain_status`, `expiration`, and `auto_renew` but the server (or an admin) has set `expired` to `True`

I'm a little worried about that last one because it could be confusing if the server set `expired` to `True` and then someone manually updated the domain's other details (or an admin set `expired` manually without changing anything else). Again, the `check_expiration()` task flips the `expired` bool back to `False` in these cases, but we're already saying we want a way to filter in situations where that task has not run. For that reason, I may drop the `expired` check.

I need to do some more testing to make sure it's working as stated above. If it is, this should help with situations where a domain has expired but...

* the `check_expiration()` task has not been run; or
* someone manually set the status to "Available"

I may reverse that to make it an "Exclude Expired" checkbox and add an "Exclude Burned" checkbox alongside. I'll have them checked by default like the "Available" status.

**Comment by chrismaddalena** [comment]
I believe v3.0.0 addressed this, so I am closing this issue. I have not heard either way, so let me know if this still needs attention!
