### ISSUE TITLE
it use much much data sending and i dont know what is send 

### ISSUE THREAD

**Issue by matty0blake** [GhostManager/Ghostwriter#181]
i track it and everytime i open ghostwriter it send about 1 to 2 kb data while y file is 60bite if it always send the whole folder it is still too much and i really like the reason of it cause it feel un safe and i already uninstall it 

 os : Ubuntu
version : 1.8.1

**Comment by chrismaddalena** [comment]
Could you explain more and provide details?

If you're looking at the request sizes compared to file sizes when uploading a file to Ghostwriter, the request will be larger than your file because it contains additional data. Your files are uploaded to your Ghostwriter server. They aren't sent anywhere else.
