### ISSUE TITLE
TinyMCE error on on open upload modal

### ISSUE THREAD

**Issue by Serizao** [GhostManager/Ghostwriter#185]
Hello,

Thanks for this project it is wonderful :)

i'have an JavaScript error when un clique on _upload evidence_ in findings and so i can't upload any picture 

![image](https://user-images.githubusercontent.com/11671895/138824536-fe111208-b214-4a37-8c95-d640ca770497.png)

do you know why maybe ?

edit:

it's because JS var  `window.parent.upload_url` is not set on url `http://127.0.0.1:8000/reporting/findings/update/[ID]`

**Comment by chrismaddalena** [comment]
@Serizao Thanks for reporting this! You are correct about the cause. The URL is only set on certain pages where the modal is expected to be used (when editing a finding in a report).

The "Upload Evidence" button is incorrectly displayed when editing a finding in the Finding Library. Attaching images to those findings is not currently supported because the evidence is expected to be specific to an individual project/report.

If you have a use case for adding evidence files to a finding template, I'd be curious to hear about them. We could potentially support that down the road.
