### ISSUE TITLE
Error: Jinja2 template syntax error: expected token 'end of print statement', got 'such' (phone of team members)

### ISSUE THREAD

**Issue by cygsecc** [GhostManager/Ghostwriter#190]
Hi,

I'm working on the deployment and the configuration of your tool for a week now and I must say that I'm impressed. The tool seems to offer lots of usefull features and I already managed to create templates that meets most of our needs.

Anyway, I'm facing an issue that I don't really understand and I can't come to resolve it. I already searched the github issues, slack channel and the internet but I can't find someone having a similar issue.

As in the template provided, I used a jinja for-loop to generate an array in my .docx for the poc of both client.contacts and team. In both of them, I retrieve the names, job-titles/role, phones and emails.

In my template I use the following jinja synthax :
```
{%tr for poc in client.contacts %}
--
{{ poc.name }} | {{ poc.role }} | {{ poc.phone }} | {{ poc.email }}
--
{%tr endfor %}

{%tr for member in team %}
--
{{ member.name }} | {{ member.role }} | {{ member.phone }} | {{ member.email }}
--
{%tr endfor %}
```
While the first array generates smoothly, the second one fails.
After some tweaking, it seems that it only happens with the `{{ member.phone }}` which return the following error in GW :
```
Jinja2 template syntax error: expected token 'end of print statement', got 'such'
```

I tried to use the {% debug %} but the result doesn't display the content of team :
```
...
'team': [{...}, {...}],
...
```

I also tried to use the `{{ team }}` and it returns the array as described in the json with the right phone number. So the information seems to be accessible.

I'm new to jinja and most of the stack used in GW so did I made a mistake ? What du you think ?

Thank you for your great job, I lurked on the trello and I can't wait to see where the project is heading !
Thomas

**Comment by chrismaddalena** [comment]
Hey @cygsecc,

I'm glad you're liking the project, and thanks for bringing this up!

Note up front: this is a simple bug I tracked down thanks to your report, but read on for more detail about this error. It's a common error message you may encounter when you edit templates.

These can be tricky to debug. I try to surface the most explicit, root-level Jinja2 errors I can, but a lot of them can be kind of cryptic or leave you wanting more info. The important part of the message is `expected token 'end of print statement'`. Everything after the comma will change from occurrence to occurrence and can lead you on a wild goose chase.

This `expected token 'end of print statement'` error means Jinja2 encountered some variable it didn't recognize. It's often a typo or missing character.

In this case, the `member.phone` isn't recognized. But it's clearly in the dictionary when we print `{{ team }}`! The explanation is I forgot to get `phone` added to the linter's template, so the linter thinks the dict doesn't have such a key.

Very soon, Ghostwriter will generate linter templates from a test database as part of the CI/CD pipeline. That will remove my potential for forgetfulness as a variable. I didn't want to push a release immediately before the holidays, but one is nearly ready. This will be fixed in that next release.

In the meantime, you can open _linting_utils.py_, scroll down to line  59, add a new line, and then add a line like this:

`"phone": "(212) 664-4444",`

Save the file and try running the linter again on your template.
