### ISSUE TITLE
Streamline installation procedure

### ISSUE THREAD

**Issue by dobin** [GhostManager/Ghostwriter#202]
"Lets try Ghostwriter", i thought this morning. "I will have it installed in 10 minutes", i thought. Took me 4 complete hours...

Things which can be improved: 
* The `shopts... cp -r .envs_template`... stuff is just plain annoying. I recommend to rename `.envs_template` to `.envs`. Thats how it will be used anyway by everyone
* Cant the DB be seeded initially automatically? Including a superuser? These commands just fail regularly
* Cant we just generate automatically a random password in the docker config for the django secret? and postgres password?
* What is the difference between local and prod? Why do we seed in local, but not in prod? Where do we set our postgres password, in both or in one? Does it need to be the same? What does "a valid postgres user" mean? Does it need to exist?
* What if I made a mistake - what needs to be rebuilt? Restartet? Why are somehow old or obsolete containers/images being used? Why do I need to throw away the whole linux container and start from the beginning when I made a little mistake?
* What are fixtures? Do i need it when i install it? Does it need to be written in the install manual?
* Mention to not use -master, only releases

I'd expect to be able to just: 
```
docker-compose -f fghostwriter.yml up
```

And it should run. No need to make the installation cumbersome and convoluted. 

related to  #201

**Comment by chrismaddalena** [comment]
Thanks for the feedback. There are reasons for each of these items. The short version is there are too many working parts that require your configuration and input for everything to be automatic.

You copy `.env_templates` to `.envs` because if you just renamed the directory and changed the original templates you'd have trouble updating the codebase later. Templates can be committed to the repository and updated without requiring you to stash your modified versions prior to running a future `git pull`. Also, a developer can configure their environment without changing a file that is tracked by the repo.

The database is only seeded once. Doing it automatically when you bring up the container would lead to issues down the line. It would overwrite any changes you make to those records and require you to maintain your changes in both the database and in the fixture files. That's no way to maintain a database, so you run the command when first setting up Ghostwriter from scratch and then never again.

When you seed the database you are giving Django the JSON "fixture" files. Files like these are how Django can import data into the database for setting up a new environment. As described in the documentation, you can review the JSON files and make adjustments prior to seeding the database.

The same goes for creating the superuser. That command can be run just once per username. It will result in an error (user already exists) otherwise.

So automating the database seeding and creation of the superuser is possible, but it'd have to be done via a setup script. You'd trade running the command for running a script that runs the command. I could see that being a little easier than running the command (especially for those new to Docker), but there are pros and cons to both options.

The local and production environments are very similar. Switching to production mostly alters how Django functions. The Django documentation outlines the finer details of what changes if you're curious. In short, a production environment uses nginx to host files instead of Django's debug web server, you can (and should) use HTTPS, and debugging is disabled.

You'll want to use the local environment if you're trying out Ghostwriter for the first time and want to experiment or customize the codebase. Otherwise, you want to use production.

The wiki walks you through starting with _local.yml_ because I recommend everyone start there. If you're trying Ghostwriter for the first time you probably want to experiment and poke around for a bit. Jumping straight into configuring nginx and HTTPS might be a bit much to get started. You can start in the local/dev environment and then switch to production with a clean database. You could just run through setup with _production.yml_ while also following the "Switch to Production" steps to configure HTTPS.

There are two sets of env files so you can manage the two environments separately. You can make them identical, configure options differently, or ignore the local templates if you never plan to use the development environment. For the PostgreSQL user, if you change the username in the _.postgres_ file it just needs to be a valid username–i.e., a username PostgreSQL will accept.

I'm not sure what you mean by "make a mistake" or "old or obsolete containers/images being used" in this context, so I'll offer a few bits of info. If you ever want to change a configuration in an env file you can change it and restart the containers. You can run `docker-compose -f production.yml down && docker-compose -f production.yml up` to restart. There's no need to destroy a container and restart unless a Docker layer has changed and the container needs to be rebuilt.

If something goes wrong with Docker you might end up with orphaned containers or volumes. Those can be "pruned" via Docker commands as needed.

In your other issue you have some output that mentions orphaned containers. If you're referencing that message then that is to be expected right now. The `graphql` container is only used in the local/dev environment (for now). If you build the local environment and switch to production Docker will see that container as "orphaned" and output a warning.

If you're updating Ghostwriter in a production environment, you'll run the `build` command to rebuild with the latest code.

Finally, you should always be able to pull the latest code. Starting with a specific release is the safest bet, but the goal is always to have the main branch be ready to go. before any code can be merged or committed it has to pass the GitHub workflows. The workflows walk through each piece of the setup process documented in the wiki and runs all unit tests.

I don't expect initial setup will change, but we're always working on the documentation. A streamlined quick start guide that covers a barebones setup might help.

**Comment by dobin** [comment]
Thanks for the update. All reasonable arguments. 

But it seems i am not the only one having a little trouble (#166, #147, #146 up until #94, #45...). Maybe a bash install script would help, or a bit more description of the whole setup - and describe how to debug common errors, maybe a FAQ.
