### ISSUE TITLE
Targets - Enter a valid IPv4 or IPv6 address

### ISSUE THREAD

**Issue by dustin-mallory** [GhostManager/Ghostwriter#211]
Hi there, I seem to have encountered some sort of bug adding targets to a project in Ghostwriter. Whenever I put in an IP address range in the target section, the form validation seems to fail. IP addresses seem to work fine though. It's entirely possible I'm using this feature in an unintended manner but I've tried multiple combinations and still can't seem to get submissions to work. Any help with this is always appreciated!

![image](https://user-images.githubusercontent.com/104014872/168293684-6ee5caf4-6328-4757-8d75-ded5f52d49c8.png)

**Comment by chrismaddalena** [comment]
Hey @dustin-mallory! Those fields are set to only allow individual IP addresses (no ranges). TL;DR, you might want to create a scope for these CIDRs instead of a target entry, but I'll look into allowing ranges in these fields.

The idea is to set individual targets of interest with an IP address or hostname. For example, you find an internal wiki that mentions a hostname that might be associated with an assessment objective, so you create a new target entry and add a description explaining why the hostname is interesting. Later, you reach that host to investigate it and can mark the host as compromised as a way to tag it as a host you can access.

For ranges that are in your scope or need to be looked at for an objective, you might want to create a scope entry. You can provide a description there as well. Scopes can contain whatever you want–i.e., hostnames, wildcard domains, IP addresses, and ranges. You can also mark scopes as disallowed (don't touch these) or "requires caution" (sensitive hosts, heavily monitored, or maybe requires notifying a POC first).

I wouldn't say what you're trying to do is "wrong," though. I can see why you might think of a CIDR as a target and want to make an entry. The Django `IPAddressField` used for the field only allows valid individual IPv4 or IPv6 addresses, but it seems easy to modify it to allow CIDRs. For example, this snippet is very old, but could probably be adapted for Django 3.2+ easily: https://djangosnippets.org/snippets/1961/

**Comment by CapAlex94** [comment]
@chrismaddalena i had the same problem with an other application. A simple workaround is to change the field from`IPAddressField ` to `TextField`. To validate the input you can do something like that:

`def clean_target(self):
        target = self.cleaned_data['target']
        try:
            ipaddress.ip_network(target)
            return target
        except ValueError:
            raise <some error>
`
This solution is more easy to implement and don't require to define a new field type.

**Comment by chrismaddalena** [comment]
Yes, that's certainly an option. Really, validating the entry is a valid address or CIDR is optional. Ghostwriter doesn't do anything with the value that would require it to be a valid address. However, I do see an interesting use case where someone might want to pull target addresses from Ghostwriter via the GraphQL API and feed them into an external tool (e.g., nmap). Knowing the values are valid addresses and CIDRs would be nice for that.

Now that v3.0.0 is tagged, I plan to revisit some of these issues to update the road map.

**Comment by chrismaddalena** [comment]
The `ip_address` field will accept IP addresses (v4 and v6) and ranges in the upcoming release.
