### ISSUE TITLE
Service.posgres.ports is invalid

### ISSUE THREAD

**Issue by yellow-starburst** [GhostManager/Ghostwriter#221]
**Describe the bug**
Having trouble installing. I did a git clone of version 3.0. 
![image](https://user-images.githubusercontent.com/39839623/173437338-ec798066-54cc-4e09-a0dd-5e31b83ddf30.png)

**To Reproduce**
Install
![image](https://user-images.githubusercontent.com/39839623/173435635-41b6a623-51b8-4f9f-8d89-fc6a88fe7d54.png)

I did a netstat and found that those ports are not in use by any other process (5432 and 8080).

**Comment by chrismaddalena** [comment]
Hey @yellow-starburst,

From the Docker output in your screenshot, the ports are invalid because they're wrapped in quotes and recognized as `PORT:PORT`. For PostgreSQL, you have `""5432":5432"`.

The good news is upgrading Docker should get you squared away. I looked at changes since v1.25.0 and Docker changed to using dotenv to parse environment variables. Versions prior to 1.26 don't use dotenv and will include any quotes around env var values. I'll update the wiki to mention this.

For reference, see bug fixes for this release: https://docs.docker.com/compose/release-notes/#1260

If you can't upgrade Docker Compose, you can try opening the `.env` file and removing the quotes around the values. I can't say for sure if that won't cause other issues if special characters are present (like in passwords), but it'd be worth a shot if you're stuck on v1.25.0.
