### ISSUE TITLE
Nginx "502 Bad Gateway" when upgrading

### ISSUE THREAD

**Issue by rybaz** [GhostManager/Ghostwriter#222]
Upgrading from 2.2.3 to 3.0.0 produces a 502 error from Nginx when trying to visit the IP.

**To Reproduce**
1. Commands
```
git pull
./ghostwriter-cli-linux down production
./ghostwriter-cli-linux build production
./ghostwriter-cli-linux up production
```

**Expected Behavior**
Expected the server to go back up with no issues since there were no errors during building.

**Server Specs:**
 - OS: Ubuntu 20.04
 - AWS EC2 t2.small

**Additional context**
I also made sure to update `docker-compose` to 1.26 to avoid the issues from #221 and updaed packages and everything to make sure nothing might have been out of date. I also attempted to add a `*` to the allowed hosts for testing, but that didn't help.

I can provide more information if needed - I expect this is a unique scenario.

**Comment by chrismaddalena** [comment]
Hey @rybaz,

There are a couple of scenarios where I'd expect to see a 502 error. Let's check a few things to rule out the common causes.

A missing hostname or IP in the allowed hosts list is the most common cause. Adding `*` as you did should rule that out as the problem. You do need to restart the server after making that change, but it sounds like you did that.

While trying to see if I could reproduce a 502, I realized I may have made a mistake in the wiki. I state you can run `./ghostwriter-cli restart production` after making a change to the config. The Docker `restart` command does not look like it picks up any changes in the _.env_ file. In retrospect, that makes sense because it just restarts the service and doesn't change the container.

To make sure Django is using your updated allowed hosts list, try bringing the containers down and back up:

`./ghostwriter-cli down production`
`./ghostwriter-cli up production`

If you still see the same response, let's see if we can narrow it down to Django or Nginx. Please try this and share your results:

1. Restart everything: `./ghostwriter-cli restart production`
2. Try connecting again
3. Get the logs for Django: `./ghostwriter-cli logs ghostwriter_django`
4. Do the same for Nginx: `./ghostwriter-cli logs ghostwriter_nginx`

What do the logs show?

If it's an issue with allowed hosts, you should see a "Bad Request (400)" page and the Django logs will look something like this:

```
INFO:     Application startup complete.
INFO 2022-06-15 02:17:34,390 on 18 140203595201352 Application startup complete.
ERROR 2022-06-15 02:17:34,839 exception 18 140203455150896 Invalid HTTP_HOST header: '127.0.0.1'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
ERROR 2022-06-15 02:17:34,839 exception 18 140203455150896 Invalid HTTP_HOST header: '127.0.0.1'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
INFO:     172.20.0.7:50290 - "GET /home/ HTTP/1.0" 400 Bad Request
```

Nginx will show a request for `https://127.0.0.1/home/` (or whatever you requested) with no errors.

**Comment by rybaz** [comment]
![image](https://user-images.githubusercontent.com/62815219/173828225-55890efe-b1c5-4111-aba6-f5f2685501d3.png)

I'm getting the 502 error in the Nginx logs as expected, but the Django logs show the following continuously, even 30+ minutes after restart. I also get a 502 over an SSH tunnel, for what it's worth:
```
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
Waiting for PostgreSQL to become available...
```
The PostgreSQL container is also up and bound/forwarding to `5432/tcp`.

Nginx (censored for private info):
```
WAN_IP - - [15/Jun/2022:12:27:27 +0000] "GET /favicon.ico HTTP/2.0" 502 559 "https://domain_name/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36" "-"
2022/06/15 12:32:41 [error] 32#32: *6 connect() failed (111: Connection refused) while connecting to upstream, client: WAN_IP, server: ghostwriter.local, request: "GET /home HTTP/2.0", upstream: "http://INTERNAL_IP:5000/home", host: "domain_name"```

**Comment by chrismaddalena** [comment]
@rybaz Thanka for that info! PostgreSQL isn't available so the 502 makes sense now. Nginx points to Django and Django hasn't started yet because it's waiting for Postgres.

What do you see if you run `./ghostwriter-cli logs postgres`?

My guess is Postgres isn't starting because of an invalid password. If that's the case, double check that the password in your old .envs/.production/.postgres file matches the one you're using now in the new .env file (`./ghostwriter-cli config get POSTGRES_PASSWORD`). Since you upgraded your Postgres database is expecting the old value, not the new randomly generated one.

**Comment by rybaz** [comment]
So that was definitely the problem, and I've made sure the files and values match now, so it's working after a container rebuild. That said, what's the best way of changing the password for the old database so that Django can authenticate (if I understand correctly)? I want to reroll it since just because it's a new instance.

**Comment by chrismaddalena** [comment]
You can absolutely change the Postgres password. You have to do that via the `psql` CLI. Start by connecting to the PostgreSQL container.

First, you will connect to Postgres and give you a bash prompt. The containers and services need to be running. You'll be root and Postgres won't like that so switch to the `postgres` user. Then you can run the CLI:

```
docker exec -it ghostwriter_postgres_1 bash
su postgres
psql
```

Finally, use the `\password` command to set a new password for the `postgres` user:

```
postgres=# \password postgres
Enter new password: 
Enter it again: 
postgres=# \q
```

That sets the new password and `\q` quits the `psql` console. Make sure you set your new password in Ghostwriter's config and then bring the containers down and back up.

```
./ghostwriter-cli down production
./ghostwriter-cli config set POSTGRES_PASSWORD <new password>
./ghostwriter-cli up production
```

Copy/paste didn't work for me, so if you try to paste the new password you might actually be setting a blank (or not what you expect to be setting).

**Comment by rybaz** [comment]
Completely fixed, thanks very much!
