### ISSUE TITLE
Template keyword references don't work outside of docx format

### ISSUE THREAD

**Issue by danms0** [GhostManager/Ghostwriter#23]
For example {{.client}} isn't filled in pptx, xlsx or json.

**Comment by chrismaddalena** [comment]
That is correct. Most of the keywords would only work in the docx report because they reference and use styles from Word.

The JSON is left untouched; all text processing comes after the JSON is generated. This is  intentional so the JSON can be either imported into Ghostwriter later (a feature coming soon for reimporting an archived report) or used by something else a user creates.

I would like to do some processing with the xlsx, but it is currently left untouched. Most of the keywords would do nothing (e.g. code_block), but replacements for `{{.client}}` would still be useful.

The pptx does use the client keyword and several settings from your `envs` directory. It will place the client name on the title slide and your company/team name, Twitter, and website on the closing slide. The finding text on the other slides should probably be axed in most cases, so no replacement is done on the keywords right now. It's very likely there will be too much text than is rally appropriate for a slide, so the text is dropped in to help provide a jumping off point for some summary bullets (or however you'd prefer to write-up the slides for a review/debrief/summary).

Going forward, there will be a lot of changes to the report generation to make the pptx and xlsx output more customizable. The xlsx output will likely strip most keywords - like code blocks and evidence files - and replace others with the appropriate text. I'm not sure about the pptx; it will get some love soon and may change in a few ways.

**Comment by danms0** [comment]
Thanks for the response. You've addressed everything so I'll close the issue.
