### ISSUE TITLE
finding.id and finding.ordering are rendered in the report and linting return a template error 

### ISSUE THREAD

**Issue by 0xkhaled** [GhostManager/Ghostwriter#246]
**Describe the bug**
I am trying to print a table where the first column is an ID and second is finding.title and third is finding.severity however each time the first column return an linting error. I tried both "finding.ordering & finding.id".

I tried also to add a line for both attributes in linting_utils.py as described in issue #190 but it didn't work.

Final note: I need to loop from 1 to totals.findings but even if this worked I will be looping from 0 to (totals.findings-1) so if there is any way for this I will be grateful.

**Comment by chrismaddalena** [comment]
Hey @0xkhaled,

The linting fails because the findings don't have an `id` or `ordering` value. Those do exist in the database but are not used in the reports. The `id` is the finding's unique identifier in the database. It's a sequential big integer that starts. It would be meaningless in a report because the finding `id` values won't be sequential and don't reset to `0` for a report–i.e., you might have three findings in a report with `id` values of `95`, `101`, and `103`.
