### ISSUE TITLE
SSTI In Word Docx templates

### ISSUE THREAD

**Issue by rschwass** [GhostManager/Ghostwriter#266]
Just getting started with this tool.
The following image demonstrates an SSTI string being placed in the Docx Template.

![image](https://user-images.githubusercontent.com/14119101/201167220-35238d6e-bdd9-417c-bb9e-e23463bb2b73.png)

The following screen shot demonstrates the execution of the exploit upon report generation.

![image](https://user-images.githubusercontent.com/14119101/201167447-a406326a-80e0-4269-83d7-5f422e13e76c.png)

This looks like SSTI with command injection/execution to me. 

Thanks.

**Comment by rschwass** [comment]
This example works for grabbing /etc/password

[SSTI2.docx](https://github.com/GhostManager/Ghostwriter/files/9983507/SSTI2.docx)

**Comment by chrismaddalena** [comment]
Hey @rschwass, thanks for bringing this up! Operations like math (`{{6*7}}`) should work with Jinja2, so that `42` output is expected. Expressions like this are often used to demo SSTI on webpages using Jinja2. You enter it as something like a username and coerce a webpage to output `42`, but in this case, you're building the template. The second expression is the more interesting as an example. I had not seen this discussed before now.

Jinja2 is not supposed to be able to execute arbitrary Python code, but the method you demonstrated works around that by taking a string, getting the class, and working toward the `os` module. Jinja2 is Python, so `"foo"` becomes an instance of `String` and you go from there.

Unfortunately, this has not been addressed in the Jinja2 project, as far as I can tell. The remediation advice from other sources is fairly generic and typical: sanitize input and restrict user input control. That's all applicable when Jinja2 is rendering an HTML template for a webpage or email. Users usually have no access to the template, so a developer only needs to properly sanitize input befopre passing it on to Jinja2.

Here you have control over the template, so options to sanitize are non-existent. You're not realy _injecting_ anything into the template. You're the developer in this scenario, so much of the remediation advice goes out the window.

I'm going to continue investigating this to see if it might be possible to restrict the Python namespace used by the Jinja2 environment. If not, the other option is making it so only an admin can edit or upload a template.

**Comment by chrismaddalena** [comment]
Adjusting the Jinja Environment to use a sandboxed variant looks promising for addressing this without having to lockdown the templates, but I need to test it to make sure it doesn't break anything. I also need to see if the sandbox has any known vulns or other issues.

![image](https://user-images.githubusercontent.com/10526228/201182309-872736af-6dbb-4bd5-95ab-fb4820dc1aed.png)
