### ISSUE TITLE
[Enhancement] Selecting the style in p tags

### ISSUE THREAD

**Issue by federicodotta** [GhostManager/Ghostwriter#296]
**Is your feature request related to a problem? Please describe.**
Hi. I would like to be able to choose the style when I add the findings (for example with  {{p finding.impact_rt }} ). By default when the "p" is chosen, Ghostwriter uses the "Normal" style but sometimes I need to apply a different style (and I can't edit the "Normal" in order to avoid issues in other portions of the document).

**Describe the solution you'd like**
Is it possible to add a parameter in the tag in which it is possible to insert the name of the style? The RichText object should allow to select a style (and example is [here](https://stackoverflow.com/questions/42143575/how-to-apply-word-styles-to-richtext-object-docxtpl-library))

**Describe alternatives you've considered**
I already tried every combination (with or without p and r, with and without _rt, with strip_html), but all the combinations bring other issues .

Thank you a lot for your help.

**Comment by chrismaddalena** [comment]
This came up recently in a Slack conversation. You are correct that the Normal style is applied automatically to any paragraph. That's typical for Word, but only sometimes what you want. You may want some paragraphs to be Justified while others are Left aligned. You can accomplish that by setting the alignment in the WYSIWYG editor. Word will apply the Normal style, but your alignment choice will override it. That's inconvenient because you have to remember to do that, and only gets more inconvenient if you have other changes besides alignment.

After all, Word's paragraph-type formatting exists for this reason. It's a tricky problem but should be solvable. It will require some time to figure out the best way to mark a paragraph with a specific style and transfer that to Word.

**Comment by federicodotta** [comment]
Hi Chris! Perfect, thanks for the help!

I tried to modify the Normal template but unfortunately that template is applied allover my document (including data in table, etc.) and consequently I cannot touch that template. My situation is the following one: I have some text that should be indented by some cm and a style similar to Normal but with a different indentation. The paragraph in the document that include the tag {{p finding.impact_rt }} is formatted with that indented style but unfortunately as you said the new sub-document applies the Normal style and the text has the indentation of the Normal. But if I add that indentation to the Normal style, a wrong indentation is applied to data in table and other data formatted with the Normal.

Thank you a lot for your help and for your great tool! I will follow the conversation you linked!

**Comment by chrismaddalena** [comment]
We merged the PR so I'm marking this issue as closed 😄
