### ISSUE TITLE
Assign client point of contacts to project

### ISSUE THREAD

**Issue by ArgentEnergy** [GhostManager/Ghostwriter#304]
Ghostwriter doesn't seem to handle cases where you have different point of contacts per report under a client. I ran into this issue with one of our customers where the point of contact is different between business units.

Having a field mapped to a project that allows a user to select multiple client point of contacts would be helpful to resolve this issue.

There doesn't seem to be a workaround for this because creating multiple clients with the same name doesn't work. I wouldn't want to do this workaround but would rather have the above feature.

**Comment by chrismaddalena** [comment]
You are right, these cases are not handled well right now. It's something I want to get resolved this year. We have an open issue for it, and it's on the project roadmap as a priority.

Since it's an open issue (https://github.com/GhostManager/Ghostwriter/issues/175), I'm going to close this one so we can consolidate the conversation, but I hear you and want to make it possible to assign/exclude contacts per project.
