### ISSUE TITLE
permissions issue on django install

### ISSUE THREAD

**Issue by craigmar** [GhostManager/Ghostwriter#320]
https://github.com/GhostManager/Ghostwriter/blob/master/compose/production/django/Dockerfile

line 51 on the docker file above throws a permission error if the install was performed as root.  I know this should not happen anyway.  To successfully install i needed to RUN chmod to change the permissions of /seed in the container to be more permissive.

**Comment by chrismaddalena** [comment]
The install is run as _root_, so that shouldn't be an issue. Docker switches to the _django_ user later (line 57), just before the entry point for the container. The _root_ user creates _django_ and sets it as the owner of everything.

Docker occasionally runs into permissions issues when the build does not complete correctly. You can fix it manually, as you did, or a rebuild usually fixes it. If you search for Docker file permission errors, it's a common pain point for Docker. The most common solution is to do what Ghostwriter's Dockerfiles do, use _root_ to run operations before creating and switching to a non-privileged user (_django_ in this case). Unfortunately, there are still some permissions issues with the odd build here and there. Eventually, I may publish Docker images on Docker Hub so they don't need to be built for installs.

I'm glad you were able to resolve it!
