### ISSUE TITLE
Add support to yubikeys and U2F as additional MFA methods

### ISSUE THREAD

**Issue by marcioalm** [GhostManager/Ghostwriter#393]
**Is your feature request related to a problem? Please describe.**
The MFA method implemented in ghostwriter is a huge step in securing the application. However, its not the most secure method since it can still be phished via tools like evilginx3 etc. Implementing U2F and hardware token MFA guarantees that credentials to ghostwriter can't be phished this way. 

This feature request is mostly a "nice to have" feature that will greatly improve the security of some deployments.

**Describe the solution you'd like**
Add yubikeys and U2F (totp) as additional MFA methods in ghostwriter. This method of MFA is a lot more secure than conventional MFA methods since they are virtually unphishable.

The following library seems to already provide this functionality: https://django-otp-yubikey.readthedocs.io/en/latest/

**Comment by chrismaddalena** [comment]
This issue is closed but tracked on the road map. I haven't found a nice way to implement YubiKeys with the auth provider, but it should be possible. In the meantime, it is possible to setup a "social" login (e.g., Google, Microsoft) and login with that. If MFA is enabled on the account, those services often support YubiKeys.
