### ISSUE TITLE
Issue with my production startup

### ISSUE THREAD

**Issue by kernelimage266** [GhostManager/Ghostwriter#45]
I'm currently trying to move to the production side of Ghostwriter, and everytime I start the production mode the webserver 80, and 443 shut off right away. I check with "nmap localhost" and I will only see it open for about 5 seconds then stops right away. I've looked at my configs in .envs and etc but haven't come to any conclusion.

My production .django is set to allow ghostwriter.local, and the production.yml is set too 0.0.0.0:80:80 and 0.0.0.0:443:443. I've also changed this and still shuts off.

Commands used:

- docker-compose -f production.yml stop; docker-compose -f production.yml rm -f; docker-compose -f production.yml build; docker-compose -f production.yml up -d 

- docker-compose -f local.yml up -d 

Thanks

**Comment by chrismaddalena** [comment]
I can see a few potential problems from what you mentioned. First, your second command used the local.yml file instead of production.yml. If you ran these two commands in this order you would build and start a production instance _and_ then start a development instance. I'm not sure if that would cause any issues but it's probably not what you intended to do.

The full production setup is covered here on the wiki: https://ghostwriter.wiki/documentation/installation/production

The really important thing to remember is when you switch to production Django's web server shuts off. Nginx takes over as the web server for hosting files. The `.django` file won't have any effect and shouldn't have any settings for ports anyway.

What controls the ports Nginx uses is this file: `compose/production/nginx/nginx.conf`

This is a basic Nginx configuration so you can make changes to it like you would any nginx.conf for any web server. If you don't see nginx on 80 or 443 (the defaults), I would check if you see nginx listening on those ports locally to determine if there is something strange happening when users try to connect externally.

If you are going to use 80/443 then the `production.yml` file shouldn't need to be changed at all.

**Comment by owtdecaf** [comment]
My team ran into the same issue yesterday. 

Ultimately we ran `docker container prune` to remove the dev instances and then started up our prod instances. I'm not super well versed in docker, but there seemed to be some conflict and it fixed the issue on our end.

**Comment by ceramic-skate0** [comment]
I am also not a docker guru but I have run into the same or a similar issue when moving from Dev/local to Production. With the Dev instance setup, I was able to complete it with minor changes to allowed list in a py file from issue #48. For production I followed the wiki article for 'Production'.  I assigned 'SECRET_KEY' (left it like the example for testing) and tried running 'docker container prune', with no luck. No domain needed to be assigned at this time and no changes made to .django or .postgres made (other than SECRET_KEY value). No error output was recorded on run of command from 'Deploy to Production' section of wiki. I ensured it used production.yml (file was also unchanged from default).

From the output I gathered there is nothing running on the ports (80/443/8000) and as a result a timed out connection.

Is there anything I could try or should have/could have done to install?

**Comment by g3ksmithington** [comment]
I'm also having a similar issue, however, I think it's related to the ghostwriter_production_nginx constantly restarting.
![Ghostwriter_nginx_container_restarting](https://user-images.githubusercontent.com/854881/86379687-c4009700-bc50-11ea-8af6-b7a902ef2c17.PNG) 

This is just after reboot of the server (I come from a Windows admin background, so that's my first step when things get wonky)

I haven't altered anything besides adding the VT API key, disabling Slack adding a secret key and updating the information. I followed along with the guide in the wiki. I did a prune while writing this post and reviewing the thread, but it didn't alter the situation at all.

While writing this, I ended up troubleshooting it, so here are my steps:
Running `docker logs --tail 50 --follow --timestamps CONTAINERID` gave me the following output:
```
2020-07-02T15:47:43.243553667Z /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
2020-07-02T15:47:43.243583466Z /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
2020-07-02T15:47:43.247424272Z /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
2020-07-02T15:47:43.248359491Z 10-listen-on-ipv6-by-default.sh: IPv6 listen already enabled, exiting
2020-07-02T15:47:43.249101271Z /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
2020-07-02T15:47:43.252052255Z /docker-entrypoint.sh: Configuration complete; ready for start up
2020-07-02T15:47:43.257114935Z 2020/07/02 15:47:43 [emerg] 1#1: cannot load certificate "/ssl/ghostwriter.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/ssl/ghostwriter.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
2020-07-02T15:47:43.257176640Z nginx: [emerg] cannot load certificate "/ssl/ghostwriter.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/ssl/ghostwriter.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
```
Apparently the SSL certificates didn't get generated. I went through the wiki again to make sure it wasn't an error on my part, I'm not sure if that's supposed to be an automated thing or if I'm supposed to manually generate the certificates, however I followed the instructions in the readme in the ssl/ directory and now the container is stable.

I'm now just getting a generic 400 Bad Request when trying to access the application, but I'll just run down that rabbit hole now.

**Comment by KitefanaticNL** [comment]
@g3ksmithington:

I had the same issue. The 400 bad request error I fixed to change the "DJANGO_ALLOWED_HOSTS=" setting in the .django config file (.envs/.production/) to allow the hosts you are connecting from. I changed it to * so every ip-address is allowed for now.

**Comment by g3ksmithington** [comment]
@KitefanaticNL yup, sorted that out. Good for someone else in the future

**Comment by selemduda** [comment]
Does anyone also face challenges when try to sign with Ghostwriter to create an email in google mail?

**Comment by chrismaddalena** [comment]
@selemduda Are you trying to implement Google accounts for SSO? You can do that, but it will require changing the codebase. There is some information here: https://github.com/GhostManager/Ghostwriter/issues/102

Otherwise, you must sign in with the initial admin user created during the installation. Once logged in, you can access the admin panel and create a new user.
