### ISSUE TITLE
Recursive Copy On Setup

### ISSUE THREAD

**Issue by jahawkins** [GhostManager/Ghostwriter#49]
When running the `mkdir .envs && cp .envs_template/.* .envs` command as the first step to setting up the application, my system included `./` and `../` in `.envs_template/.*` so it copied all of the application files. I didn't catch the mistake at first and ran into an infinite recursive build...

I would recommend changing the command in the wiki to `mkdir .envs && cp -r .envs_template/.local .envs && cp -r .envs_template/.production .envs`.

**Comment by mattreduce** [comment]
I've been running `cp -R .envs_template .envs` to create the new directory and copy over all template contents in one shot

**Comment by Cashiuus** [comment]
I encountered the same issue and should've came here a lot sooner! I'm on Debian 10, running BASH, and recursive copy of hidden files is treated differently by default I guess than what you are using (zsh?). My system also attempts to include `.envs_template/..` in the copy operation due to the placement of the wildcard. You can see evidence of this attempt by debugging the command via: `strace cp -R .envs_template/.* .envs`

I would account for this in your setup instructions, by either specifying the dirs to copy, or adding an additional line. I'm not sure how shell options affect the platform you are using, but here was my fix (enabling copying of hidden files/dirs first):

```
shopt -s dotglob
cp -r .envs_template/* .envs/
```
