### ISSUE TITLE
Doesn't allow servers with same IP.

### ISSUE THREAD

**Issue by mynoc96** [GhostManager/Ghostwriter#511]
**Describe the bug**
You can't create a server with a static IP if it already exists in the server list.

**To Reproduce**
1. Go to 'Servers->Add new server'
2. Fill the form required fields and enter an address of 10.10.10.10.
3. Select Submit.
4. Repeat steps 1-3.
5. See error

**Expected Behavior**
A warning would be useful, but there are cases where the same cloud infrastructure has multiple servers with the same IP. It should allow me to either be stupid or capture my crazy edge cases. :-)

**Server Specs:**
 - OS: Ubuntu 22.04.4 LTS
 - Docker 24.0.7
 - Ghostwriter 4.2.5

**Comment by chrismaddalena** [comment]
Hey @mynoc96, the server library requires the IP address to be unique because it's intended to track long-running servers that get reused or have a dedicated purpose–e.g., like a dedicated hashcracker or a server (re)used as a C2 team server. These are usually servers you own and operate.

It's important that each server be unique to avoid conflicts. If two identical entries exist and someone checks out one of those servers, it looks like the server is available because the duplicate is still in the available pool of servers. That could lead to two people stepping on each other because each person thinks they reserved the use of the server.

With internal IP addresses, you could have two such servers with the same address in different networks, but that should be a rare edge case. In those cases, the servers may have a unique external IP address you can use for the entry. You can track the shared IP address as an additional IP address. You can even mark the shared IP address as the primary address for both servers. For example, both of these servers have a unique identifier but share the IP address 192.168.100.100. Both servers have the shared IP address flagged as their primary IP address, so they appear as 192.168.100.100 when viewed.

<img width="373" alt="image" src="https://github.com/user-attachments/assets/0af7a94c-ca38-485b-b682-0dc34448643d">

I don't see a way to remove the unique constraint without negatively impacting server check outs, but you should be able to use the solution I detailed above for tracking servers that share an IP address.

**Comment by mynoc96** [comment]
Thanks for the response. Your recommendation should work. I appreciate it.

**Comment by chrismaddalena** [comment]
Cool, I'm glad to hear it! I'll close this out. Let us know if anything else comes up.
