### ISSUE TITLE
WYSIWYG and report output

### ISSUE THREAD

**Issue by eddiezab** [GhostManager/Ghostwriter#52]
Using the HTML markup of the WYSIWYG editor (e.g., links, br, etc), render properly in Ghostwriter however, when exporting a report HTML formatting is placed in the document literally (e.g., <a href="" etc) instead of creating a link.

**Comment by chrismaddalena** [comment]
Thank you for raising this as an issue. For some background, not inserting links into the report output is intentional. It is a personal preference, not including clickable links in a report. This decision predated the WYSIWYG editor, when there was no option to even include a link that you might expect to produce a link in the report output.

Now that a user can create a link and might expect it to be reflected in a report, we should address this. At the very least, the HTML should be stripped to leave just the plaintext link in the report.

I will look at the libraries Ghostwriter uses to create the reports (e.g., python-docx) to see how links can be handled. I _think_ the only report that could support a hyperlink is the Word report and python-docx may have a way to create a link.

**Comment by chrismaddalena** [comment]
I have reviewed this issue and found a solution. It will be committed here shortly.

Ghostwriter now supports hyperlinks in the Word reports. There is one small issue that will probably never come up:

Due to how text "runs" work, a hyperlink that is partially bolded/italicized will actually appear as two or more links. This is better demonstrated in an example...

hxxps://example[.]com/**some-blog-post.html**

This link would appear in the Word report as a hyperlink and function normally. Clicking the link would reveal the bold half of the link to be a second, separate link. Both links would point to the full URL, but only half of the text would turn purple after a click.

Other mixed styles (e.g., inline code, underline) would also cause this. I don't see any scenario where anyone would want to partially bold/italicize one piece of a hyperlink, so this is a minor problem.
