### ISSUE TITLE
Rich Code feature breaks when a span tag is provided as text

### ISSUE THREAD

**Issue by ArgentEnergy** [GhostManager/Ghostwriter#535]
**Describe the bug**
The Rich code feature has a bug where it will prevent the report from being generated when there is span tag. I had an application that sent a JSON request with HTML in one of the fields. The report failed to generate with an error "unexpected char '&' at 1029..." TinyMCE will encode the HTML as &lt; and &gt; but when it gets rendered from Jinja an error is thrown and the report fails to generate. This seems to only happen with the span tag as far as I know because when I removed the span tag in the JSON, the report generation worked.

**To Reproduce**
1. Create a report with a finding. 
2. Click the {;} button to create a rich code text area.
3. Paste the following in the rich code area:
```
{"htmlBody":"<div>{FirstName}....</div><div>{{{<span style=\"background-color: rgb(255, 255, 255); color: rgb(35, 31, 32);\">Contact.link</span>}}}</div><div>Test</div>"}
```
4. Save the finding.
5. Click the report generation for Word documents and see the error.

**Expected Behavior**
The report should be generated as expected with the text formatted properly.

**Server Specs:**
 - Ghostwriter 4.3.1

![Screenshot 2024-10-01 at 4 41 20 PM](https://github.com/user-attachments/assets/7c38921b-3b15-4fa1-acff-84fd4779c981)

**Comment by ArgentEnergy** [comment]
I was able to get around this by removing the span tag from the sample HTTP request in the report but there might be situations where an application requires it for the payload to work. The application should treat it as text.

**Comment by ColonelThirtyTwo** [comment]
Ghostwriter's Jinja templating is trying to interpret the `{{` and `}}` parts of the `{{{<span ...}}}` segment as a Jinja expression, which does not parse. Easiest fix is to wrap the code segment in `{% raw %}...{% endraw %}` so that Jinja will ignore it:

```
{% raw %}{"htmlBody":"<div>{FirstName}....</div><div>{{{<span style=\"background-color: rgb(255, 255, 255); color: rgb(35, 31, 32);\">Contact.link</span>}}}</div><div>Test</div>"}{% endraw %}
```

It's not the most intuitive behavior, but there's not a whole lot Ghostwriter can do about it - we can't parse the HTML and figure out that it's a code block until Jinja is finished evaluating it. Plus someone may want to do Jinja substitutions inside of the code block.

**Comment by chrismaddalena** [comment]
I think this was resolved with the above response, so I will close this. If any additional assistance is needed, feel ree to re-open it.
