### ISSUE TITLE
Not able to mark domains as expired

### ISSUE THREAD

**Issue by ksjc** [GhostManager/Ghostwriter#62]
I have domains that have expired but the status is not changing to expired.  When I look at a single domain the expired icon appears.  I have tried to mark the domain as expired but nothing happens to the status.  The only way to change the status is through the admin page.

**Comment by chrismaddalena** [comment]
That is somewhat intentional, but we can offer a manual option. We haven't surfaced the  "Expired" boolean field in the regular interface because that's all intended to be automatic. If you have the Django Q task for checking expiration configured to run daly, Ghostwriter will flip domains to expired as they expire. If they are set to Auto-Renew, the task bumps the expiration date +1 year.

I'll make a note to add a manual control in the regular interface in a future update.

**Comment by ksjc** [comment]
Thanks for the update. It would be nice to have the domains  flip themselves.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
